# Global acquisition setting
acquisition:
  library: 'autoscript'  # Microscope control library. Possible values: 'AS'
  slice_distance: 10e-9  # Slicing step
  imaging_angle: 90  # Angle between sample plane and e-beam (degrees)
  drift_correction: 'y' # Drift correction strategy. Possible values 'y' for simple y correction
  additive_beamshift: (0, 0) # Additive beam shift applied in every cycle
  setting_file: 'microscope_settings.yaml' # Actual microscope setting


microscope:
  ip_address: 'localhost'  # ASV server address
  stage_tolerance: 1e-7  # Maximal stage error that is considered as ok
  stage_trials: 3  # Number of trials to reach the goal position before raise error
  beamshift_tolerance: 50e-9 # Maximal beam shift error that is considered as ok
  beam_shift_to_stage_move: (-1, -1) # Axis transformation between beamshift and stage

# Directories
dirs:
  output_images: 'images'
  log: 'logs'

