acquisition:
  criterion_name: image_acquisition
  image_name: image_acquisition
  imaging_enabled: true
  wd_correction: 7.88010753607e-09
  y_correction: 6.15661475326e-09
autofunction:
- af_area:
    height: 0
    width: 0
    x: 0
    y: 0
  autofunction: StepAutoFunction
  criterion_name: working_distance - image
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  image_name: working_distance - image
  mask_name: none
  max_attempts: 8
  name: working_distance - image
  sweeping_max_limits:
  - 0.0005
  - 0.07
  sweeping_range:
  - -0.0001
  - 0.0001
  sweeping_steps: 3
  sweeping_strategy: BasicInterleavedSweeping
  sweeping_total_cycles: 1
  variable: electron_beam.working_distance
- af_area:
    height: 0
    width: 0
    x: 0
    y: 0
  autofunction: LineAutoFunction
  criterion_name: working_distance - line
  delta_x: 0
  execute_resolution: 0
  execute_slices: 0
  forbidden_sections:
  - 0
  image_name: working_distance - line
  keep_time: 10
  mask_name: none
  max_attempts: 8
  name: working_distance - line
  pre_imaging_delay: 1
  sweeping_max_limits:
  - 0.0005
  - 0.07
  sweeping_range:
  - -0.0001
  - 0.0001
  sweeping_steps: 20
  sweeping_strategy: BasicSweeping
  sweeping_total_cycles: 4
  variable: electron_beam.working_distance
contrast_brightness:
  acb_area:
    height: 0
    width: 0
    x: 0
    y: 0
  acb_enabled: true
  allowed_minimal_band: 0.5
  allowed_saturation: 0.01
  mask_name: none
  p_brightness: 10
  p_decrease_contrast: 10
  p_increase_contrast: 10
criterion_calculation:
- border: 0.3
  criterion: frc_criterion
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: image_acquisition
  tile_size: 3.0e-06
- border: 0
  criterion: bandpass_criterion
  detail:
  - 1.0e-07
  - 3.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: working_distance - image
  tile_size: 0
- border: 0
  criterion: bandpass_criterion
  detail:
  - 1.0e-07
  - 3.5e-07
  final_regions_resolution: min
  final_resolution: min
  mask_name: none
  name: working_distance - line
  tile_size: 0
dirs:
  log: logs
  output_images: images
  template_matching: templates
drift_correction:
  driftcorr_areas:
  - height: 0
    width: 0
    x: 0
    y: 0
  min_confidence: 0
  rescan: 20
  type: template_matching
email:
  password_file: email_password.txt
  receiver: pavel.krep@gmail.com
  sender: pavel.emcf@gmail.com
general:
  additive_beam_shift:
  - 0
  - 0
  library: autoscript
  log_level: 10
  sem_settings_file: microscope_settings.yaml
  variables_to_save:
  - position
  - electron_beam.working_distance
  - electron_beam.stigmator
  - electron_beam.lens_alignment
  - electron_beam.beam_shift
  - electron_beam.detector_contrast
  - electron_beam.detector_brightness
  - electron_beam.dwell_time
image:
- bit_depth: 16
  dwell: 1.0e-06
  field_of_view:
  - 3.19e-05
  - 2.12666666667e-05
  images_line_integration: 1
  name: image_acquisition
  pixel_size: 5.0e-09
- bit_depth: 8
  dwell: 1.0e-06
  field_of_view:
  - 3.19e-05
  - 2.12666666667e-05
  images_line_integration: 1
  name: working_distance - image
  resolution:
  - 6144.0
  - 4096.0
- bit_depth: 8
  dwell: 1.0e-06
  field_of_view:
  - 3.19e-05
  - 2.12666666667e-05
  images_line_integration: 1
  name: working_distance - line
  resolution:
  - 6144
  - 4096
mask:
- downsampling_factor: 4
  fill_holes: true
  iterative_training: false
  mask_image_li: 32
  min_area: 100
  min_fraction: 0.1
  model_path: /home/pavelkrep/data/deepmib_test/seg_exported
  name: mask
  patch_size:
  - 128
  - 128
  threshold: 0.5
  update_mask: true
microscope:
  beam_shift_tolerance: 5.0e-08
  ip_address: 10.56.91.11
  relative_beam_shift_to_stage:
  - 1
  - 1
  stage_tolerance: 1e-7
  stage_trials: 3
milling:
  direction: -1
  fiducial_area:
    height: 0
    width: 0
    x: 0
    y: 0
  fiducial_margin: 1.0e-06
  fiducial_rescan: 3
  fiducial_update: 300
  milling_area:
    height: 0
    width: 0
    x: 0
    y: 0
  milling_depth: 1.0-6
  milling_enabled: true
  minimal_similarity: 0.9
  pattern_file: CCS
  settings_file: fib_microscope_settings.yaml
  slice_distance: 1.0e-08
  variables_to_save:
  - position
  - ion_beam.working_distance
  - ion_beam.beam_shift
  - ion_beam.detector_contrast
  - ion_beam.detector_brightness
